export const CHANGE_VIDEO = "CHANGE_VIDEO";
export const CURRENT_VIDEO = "CURRENT_VIDEO";
export const PLAY_PAUSE_VIDEO = "PLAY_VIDEO";
export const VOLUME_CHANGE_VIDEO = "VOLUME_CHANGE_VIDEO";
export const TOGGLE_FULLSCREEN_VIDEO = "TOGGLE_FULLSCREEN_VIDEO";
