export const CHANGE_VIDEO = 'CHANGE_VIDEO';
export const CURRENT_VIDEO = 'CURRENT_VIDEO';
export const PLAY_PAUSE = 'PLAY_PAUSE';
export const VOLUME_CHANGE = 'VOLUME_CHANGE';
export const TOGGLE_FULLSCREEN = 'TOGGLE_FULLSCREEN';
